name: Post-Push workflow - Extract PBIX Metadata

on:
  workflow_dispatch:
  push:
    paths:
    - '**/*.pbix'

jobs:
  extract_pbix_metadata:
    runs-on: windows-latest
    environment: PowerBI
    env:
      PBI_TENANT_ID: ${{ secrets.PBI_TENANT_ID }}
      PBI_CLIENT_ID: ${{ secrets.PBI_CLIENT_ID }}
      PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
      PBI_WORKSPACE_ID: ${{ secrets.PBI_WORKSPACE_ID }}
      GIT_EVENT_BEFORE: ${{ github.event.before }}
      GIT_EVENT_AFTER: ${{ github.event.after }}

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: List changed PBIX files
      run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} --diff-filter=ACM "*.pbix"
    
    - name: Extract PBIX Metadata
      run: |
          ./src/Extract-PBIXMetadata.ps1
      shell: pwsh
    - name: Push PBIX MetaData
      run: |
          git config --global user.name '${{ github.workflow }}'
          git config --global user.email '${{ github.workflow }}@users.noreply.github.com'
          git add .
          git commit -am "${{ github.workflow }}"
          git push

