name: Post-Push workflow - Extract PBIX Metadata

on:
  workflow_dispatch:
  push:
    paths:
    - '**/*.pbix'

jobs:
  extract_pbix_metadata:
    runs-on: windows-latest
    environment: PowerBI
    env:
      PBI_TENANT_ID: ${{secrets.PBI_TENANT_ID}}
      PBI_CLIENT_ID: ${{secrets.PBI_CLIENT_ID}}
      PBI_CLIENT_SECRET: ${{secrets.PBI_CLIENT_SECRET}}
      PBI_WORKSPACE_ID: ${{secrets.PBI_WORKSPACE_ID}}

    steps:
    - uses: actions/checkout@v2
    - name: Extract PBIX Metadata
      run: |
          ./src/Extract-PBIXMetadata.ps1
      shell: pwsh
    - name: Push PBIX MetaData
      run: |
          git config --global user.name 'Post-Push workflow - Extract PBIX Metadata'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add .
          git commit -am "Extract PBIX Metadata"
          git push

